name: Feature
type: feature
description: >-
  A new piece of functionality or an enhancement to the product that delivers
  value to the end-user.
body:
  - type: markdown
    attributes:
      value: >-
        A feature is a new piece of functionality or an enhancement to the
        product that delivers value to the end-user. Use this template to
        request new capabilities or improvements that will benefit users of the
        system.

        Please provide clear details using the "What, Why, How" approach to help
        us understand and build what you need.

  - type: textarea
    id: what
    attributes:
      label: What?
      description: >-
        Describe exactly what functionality should be added or enhanced. What
        will users be able to do with this feature?
      placeholder: |-
        Example:

        Add a new SerialNumber type that links to InventoryItem with a unique
        serial number string. Update createInventoryItem mutation to optionally
        accept serial numbers. Add new mutations "assignSerialNumber",
        "removeSerialNumber".

        Add serial number filtering to inventory queries to find items by
        specific serial numbers.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: >-
        Explain why this feature is needed and what value it delivers to
        end-users. What problem does it solve? What benefit does it provide?
      placeholder: |-
        Example:

        Many warehouse customers need to track individual serial numbers for
        high-value items, electronics, or compliance requirements. Currently,
        they can only track quantities at the SKU level, which doesn't meet
        regulatory needs for industries like pharmaceuticals or electronics.

        Serial number tracking would enable customers to trace individual items
        through receiving, storage, picking, and shipping, supporting warranty
        tracking, recalls, and compliance reporting.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: >-
        List the criteria that must be fulfilled for this feature to be
        considered complete. Focus on user-facing outcomes and functionality.
      placeholder: |-
        Example:

        - [ ] createInventoryItem mutation accepts optional serialNumbers array parameter
        - [ ] assignSerialNumber mutation created and accepts inventoryItemId and serialNumber
        - [ ] removeSerialNumber mutation created and accepts serialNumberId
        - [ ] Serial number uniqueness constraint enforced (returns error for duplicates)
        - [ ] inventoryItems query accepts serialNumber filter parameter
        - [ ] InventoryItem.serialNumbers field returns array of SerialNumber objects
        - [ ] API documentation updated with serial number field descriptions and examples
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How? (Optional)
      description: >-
        If you have ideas about how this feature should be implemented or how
        users should interact with it, describe them here.
      placeholder: |-
        Example:

        Extend the existing GraphQL schema with a SerialNumber type containing
        fields "id", "serialNumber" (unique string), "inventoryItemId", and
        "status". Add serial number array input to createInventoryItem mutation.
        Create new mutations for managing serial numbers post-creation. Update
        the InventoryItem type to include a serialNumbers field that returns
        associated serial numbers. Add serial number filtering to existing
        inventory queries.

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment (Optional)
      description: >-
        If known, describe what systems, components, and/or processes will be
        affected by this feature.
      placeholder: |-
        Example:

        - Affected systems: GraphQL API, Database schema, existing inventory queries
        - Database changes: New serial_numbers table with unique constraints
        - API changes: New SerialNumber type, extended InventoryItem type
        - Dependencies: Existing InventoryItem type, createInventoryItem mutation
        - Breaking changes: None (additive only)
        - Performance considerations: Additional database joins for serial number queries
    validations:
      required: false
