name: Business Goal
description: Define a business objective for the planning repository
body:
  - type: markdown
    attributes:
      value: |
        Use this template to define high-level business objectives that will be broken down into specific Features and Tasks.
        This template is primarily for use in the planning repository.
        
- type: input
  id: objective
  attributes:
    label: Business Goal
    description: Briefly describe the objective (e.g., Reduce churn by 20%)
    placeholder: "e.g., Improve onboarding to reduce churn by 20%"
  validations:
    required: true
      
- type: textarea
  id: details
  attributes:
    label: Details & Success Metrics
    description: What outcome do you want? How will you measure success? (List metrics)
    placeholder: "Describe the outcome and add measurable success criteria..."
  validations:
    required: true
      
      
      
      