name: Defect
description: |-
  Report a feature that does not work as documented or behaves differently
  than expected
body:
  - type: markdown
    attributes:
      value: |-
        A defect means the software is not working as it should according to
        documentation or requirements. Use this template when something is
        broken or works differently than expected.

        Please provide clear details so we can understand and fix the problem.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |-
        Please provide as much detail as possible about what is not working.
        Include the problem summary, relevant documentation links, and any
        additional context that will help us understand and fix the issue.
      placeholder: |-
        The createInventoryItem mutation fails with a validation error when
        using valid SKU formats. According to the GraphQL API documentation
        (https://docs.pyck.cloud/graphql-api/mutations/create-inventory-item),
        SKUs should support alphanumeric characters with optional hyphens and
        underscores, but the mutation consistently rejects SKUs containing
        hyphens with "Invalid SKU format" errors.
        
        This affects our warehouse onboarding process since many clients use
        hyphenated SKU formats for their existing inventory systems.
    validations:
      required: true

  - type: textarea
    id: observed_behavior
    attributes:
      label: Observed Behavior
      description: |-
        Please describe what you observe happening (the wrong behavior)
      placeholder: |-
        When I call the createInventoryItem mutation with a valid SKU
        (format: "WH-ABC-001"), the GraphQL API returns a validation error:
        "Invalid SKU format". The mutation fails even though the SKU follows
        the documented format requirements. This happens consistently with
        any SKU containing hyphens.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: |-
        Please describe what you expected to happen (the correct behavior)
      placeholder: |-
        According to the GraphQL API documentation, the createInventoryItem
        mutation should accept SKUs in alphanumeric format with optional
        hyphens and underscores. The mutation should successfully create an
        inventory item and return the new item's ID when provided with valid
        input data including a properly formatted SKU.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Reproduction Steps
      description: |-
        Please list the steps needed to make this problem happen again
      placeholder: |-
        1. Open GraphQL playground or API client
        2. Execute createInventoryItem mutation with these variables:
           - name: "Test Product"
           - sku: "WH-ABC-001"
           - repositoryId: "valid-repo-id"
        3. Submit the mutation request
        4. Observe the validation error response
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: |-
        Which version has this problem? Please provide the version number and/or commit ID
      placeholder: |-
        v0.1.2 (d34db33f)
    validations:
      required: true

  - type: textarea
    id: proposed_fix
    attributes:
      label: Suggested Solution (Optional)
      description: |-
        If you have ideas about how to fix this, please share them with us
      placeholder: |-
        The createInventoryItem mutation should properly validate SKU format
        and accept hyphens as documented. The validation logic should check
        for alphanumeric characters plus hyphens/underscores instead of
        rejecting valid SKU formats that contain hyphens.
    validations:
      required: false

